"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { useState } from "react";
import Cart from "@/Components/Cart";

const inter = Inter({ subsets: ["latin"] });

export const Metadata = {
  title: "Cosmetics Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showCart, setShowCart] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Navbar setShowCart={setShowCart} />
          {showCart && <Cart setShowCart={setShowCart} />}
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
